// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfvxHLcCFetoO8taKHnvimiaanpR49UfE',
    appId: '1:1049365186984:web:88abcd6b81d796605ef59d',
    messagingSenderId: '1049365186984',
    projectId: 'polyapp-by-youxu',
    authDomain: 'polyapp-by-youxu.firebaseapp.com',
    storageBucket: 'polyapp-by-youxu.firebasestorage.app',
    measurementId: 'G-S3EVGJW4TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFM4E9CGnUqyUENSiOke-qcAF6YTufwN4',
    appId: '1:1049365186984:android:b9fc328cfe4cf79a5ef59d',
    messagingSenderId: '1049365186984',
    projectId: 'polyapp-by-youxu',
    storageBucket: 'polyapp-by-youxu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVzGPveUY8AraoGPCyMFTXiAmyY84eOb4',
    appId: '1:1049365186984:ios:a58431881d0cf2c85ef59d',
    messagingSenderId: '1049365186984',
    projectId: 'polyapp-by-youxu',
    storageBucket: 'polyapp-by-youxu.firebasestorage.app',
    iosBundleId: 'com.example.polyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVzGPveUY8AraoGPCyMFTXiAmyY84eOb4',
    appId: '1:1049365186984:ios:a58431881d0cf2c85ef59d',
    messagingSenderId: '1049365186984',
    projectId: 'polyapp-by-youxu',
    storageBucket: 'polyapp-by-youxu.firebasestorage.app',
    iosBundleId: 'com.example.polyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfvxHLcCFetoO8taKHnvimiaanpR49UfE',
    appId: '1:1049365186984:web:6616b6dabe57568c5ef59d',
    messagingSenderId: '1049365186984',
    projectId: 'polyapp-by-youxu',
    authDomain: 'polyapp-by-youxu.firebaseapp.com',
    storageBucket: 'polyapp-by-youxu.firebasestorage.app',
    measurementId: 'G-K0KC1C26EL',
  );
}
